application: osa-app
version: alpha-003
runtime: go
api_version: go1
threadsafe: true

handlers:

# Needed for Cloud Endpoints
- url: /_ah/spi/.*
  script: _go_app

- url: /(.+)
  static_files: frontend/\1
  upload: frontend/(.+)

- url: /
  static_files: frontend/index.html
  upload: frontend/index\.html
