application: osa-app
version: alpha-001
runtime: go
api_version: go1

handlers:

- url: /api/v1.0/members
  script: _go_app
  login: optional

- url: /api/v1.0/events
  script: _go_app
  login: optional

- url: /api/v1.0/login
  script: _go_app
  login: optional

- url: /api/v1.0/logout
  script: _go_app
  login: optional

- url: /api/.*
  script: _go_app
  login: required

- url: /(.+)
  static_files: frontend/\1
  upload: frontend/(.+)

- url: /
  static_files: frontend/index.html
  upload: frontend/index\.html

