application: osa-app
version: alpha-001
runtime: go
api_version: go1

handlers:

- url: /api/v1.0/event_signup
  script: _go_app
  login: required

- url: /api/.*
  script: _go_app

- url: /(.+)
  static_files: frontend/\1
  upload: frontend/(.+)

- url: /
  static_files: frontend/index.html
  upload: frontend/index\.html
